### ISSUE TITLE
App crashes when using app:layout_behavior="behaviorName"

### ISSUE THREAD

**Issue by noMuffin** [Clans/FloatingActionButton#185]
I wanted to use a behavior for the visibility of the floatingactionbutton while scrolling in a nestedscrollview. 
The app crashes when the activtiy with the layout with the floatingactionbutton starts.

I think you can fix it, if you add the FloatingActionButton.Behavior class to your floatingactionbutton library. Than i could extend my Behavior with something like:

`public class ScrollAwareFABBehavior extends com.github.clans.fab.FloatingActionButton.Behavior {}`

Error message:

    java.lang.ClassCastException: com.github.clans.fab.FloatingActionButton cannot be cast to android.support.design.widget.FloatingActionButton
                                         at android.support.design.widget.FloatingActionButton$Behavior.layoutDependsOn(FloatingActionButton.java:405)
                                         at android.support.design.widget.CoordinatorLayout$LayoutParams.dependsOn(CoordinatorLayout.java:2411)
                                         at android.support.design.widget.CoordinatorLayout$1.compare(CoordinatorLayout.java:123)
                                         at android.support.design.widget.CoordinatorLayout$1.compare(CoordinatorLayout.java:118)
                                         at android.support.design.widget.CoordinatorLayout.selectionSort(CoordinatorLayout.java:2662)
                                         at android.support.design.widget.CoordinatorLayout.prepareChildren(CoordinatorLayout.java:571)
                                         at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:616)
                                         at android.view.View.measure(View.java:18794)
                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                         at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                         at android.view.View.measure(View.java:18794)
                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                         at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                         at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                         at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                         at android.view.View.measure(View.java:18794)
                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                         at android.view.View.measure(View.java:18794)
                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                         at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                         at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                         at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                         at android.view.View.measure(View.java:18794)
                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                         at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                         at android.view.View.measure(View.java:18794)
                                         at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                                         at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                         at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                         at android.view.Choreographer.doFrame(Choreographer.java:606)
                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                         at android.os.Handler.handleCallback(Handler.java:739)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:148)
                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by rsd-raul** [comment]
For some reason I can't make it work from the .xml either 

In any case, for controlling the FAB (or FAM in my case) behaviour while in a NestedScrollView I have used this code:

```
NestedScrollView scrollView = (NestedScrollView) activity.findViewById(R.id.scrollView);
scrollView.setOnScrollChangeListener(new NestedScrollView.OnScrollChangeListener() {
    @Override
    public void onScrollChange(NestedScrollView v, int scrollX, int scrollY,
                               int oldScrollX, int oldScrollY) {
        if (scrollY - oldScrollY > 0)
            fam.hideMenu(true);
        else
            fam.showMenu(true);
    }
});
```

On the other hand, I'm using a Coordinator as a root layout, If that's your case you can also set your custom behaviour like this:

```
CoordinatorLayout.LayoutParams params = (CoordinatorLayout.LayoutParams) fam.getLayoutParams();
params.setBehavior(new FloatingActionMenuBehavior());
fam.requestLayout();
```

Sadly, both options set the behaviour programmatically... But well... What are you gonna do :S

Ps: fam reffers to:
```
FloatingActionMenu fam = (FloatingActionMenu) findViewById(R.id.menuFAB);
```

**Comment by noMuffin** [comment]
@rsd-raul Thanks you very much! The first option worked! So simple ^^
But could you show me your "FloatingActionMenuBehavior" as well? Im interested how you hide your button with the coordinatorlayout, im new to the behavior things ^^

**Comment by rsd-raul** [comment]
I'm glad it worked. About the behaviour, I don't use mine to hide and show the FAM, but to raise and lower it when a Snackbar spawn.

Ps: Right know I'm not really using anything for the scroll as my NestedScroll is now inside a ListFragment and I don't seem to be able to retrieve the NestedScrollView at Activity Creation... I'll wait till the ListFragment is completed before going into that.
