### ISSUE TITLE
OPPO A33 phone  Absolutely crash

### ISSUE THREAD

**Issue by jayronlou** [Clans/FloatingActionButton#376]
crash  log:
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.superstar.fantuan/com.asiainno.starfan.main.ui.MainActivity}: android.view.InflateException: Binary XML file line #119: Error inflating class com.asiainno.starfan.widget.FloatingActionButton
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2587)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659)
       at android.app.ActivityThread.access$1000(ActivityThread.java:169)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1467)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:159)
       at android.app.ActivityThread.main(ActivityThread.java:5671)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
Caused by android.view.InflateException: Binary XML file line #119: Error inflating class com.asiainno.starfan.widget.FloatingActionButton
       at android.view.LayoutInflater.createView(LayoutInflater.java:633)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at com.asiainno.starfan.base.BaseSFDC.setView(Unknown Source)
       at com.asiainno.starfan.main.dc.MainDC.(Unknown Source)
       at com.asiainno.starfan.main.manager.MainManager.(Unknown Source)
       at com.asiainno.starfan.main.ui.MainActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:6156)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2508)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659)
       at android.app.ActivityThread.access$1000(ActivityThread.java:169)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1467)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:159)
       at android.app.ActivityThread.main(ActivityThread.java:5671)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at com.asiainno.starfan.base.BaseSFDC.setView(Unknown Source)
       at com.asiainno.starfan.main.dc.MainDC.(Unknown Source)
       at com.asiainno.starfan.main.manager.MainManager.(Unknown Source)
       at com.asiainno.starfan.main.ui.MainActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:6156)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2508)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659)
       at android.app.ActivityThread.access$1000(ActivityThread.java:169)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1467)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:159)
       at android.app.ActivityThread.main(ActivityThread.java:5671)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
Caused by android.content.res.Resources$NotFoundException: File res/mipmap-xhdpi-v4/ic_add.png from drawable resource ID #0x7f030115

       at android.content.res.Resources.loadDrawableForCookie(Resources.java:2635)
       at android.content.res.Resources.loadDrawable(Resources.java:2519)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
       at android.widget.ImageView.(ImageView.java)
       at android.widget.ImageButton.(ImageButton.java)
       at android.widget.ImageButton.(ImageButton.java)
       at com.asiainno.starfan.widget.FloatingActionButton.(Unknown Source)
       at com.asiainno.starfan.widget.FloatingActionButton.(Unknown Source)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at com.asiainno.starfan.base.BaseSFDC.setView(Unknown Source)
       at com.asiainno.starfan.main.dc.MainDC.(Unknown Source)
       at com.asiainno.starfan.main.manager.MainManager.(Unknown Source)
       at com.asiainno.starfan.main.ui.MainActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:6156)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2508)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659)
       at android.app.ActivityThread.access$1000(ActivityThread.java:169)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1467)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:159)
       at android.app.ActivityThread.main(ActivityThread.java:5671)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
Caused by java.io.FileNotFoundException: res/mipmap-xhdpi-v4/ic_add.png
       at android.content.res.AssetManager.openNonAssetNative(AssetManager.java)
       at android.content.res.AssetManager.openNonAsset(AssetManager.java:446)
       at android.content.res.Resources.loadDrawableForCookie(Resources.java:2628)
       at android.content.res.Resources.loadDrawable(Resources.java:2519)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
       at android.widget.ImageView.(ImageView.java)
       at android.widget.ImageButton.(ImageButton.java)
       at android.widget.ImageButton.(ImageButton.java)
       at com.asiainno.starfan.widget.FloatingActionButton.(Unknown Source)
       at com.asiainno.starfan.widget.FloatingActionButton.(Unknown Source)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at com.asiainno.starfan.base.BaseSFDC.setView(Unknown Source)
       at com.asiainno.starfan.main.dc.MainDC.(Unknown Source)
       at com.asiainno.starfan.main.manager.MainManager.(Unknown Source)
       at com.asiainno.starfan.main.ui.MainActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:6156)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2508)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659)
       at android.app.ActivityThread.access$1000(ActivityThread.java:169)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1467)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:159)
       at android.app.ActivityThread.main(ActivityThread.java:5671)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by Clans** [comment]
This is not my library.

**Comment by jayronlou** [comment]
It's your library ，only I include the source code,change the package.Because only this one phone crash, I had add try catch exception ,then it was solved
