### ISSUE TITLE
ndroid.view.InflateException: Binary XML file line #54: Binary, For input string: "res/drawable/edit_text_material.xml"

### ISSUE THREAD

**Issue by m2kk** [Clans/FloatingActionButton#474]
Basically just by integrating "new" implementation ('com.android.billingclient:billing:2.0.3') library,
suddenly the following crash occurs, but I'm not able to resolve it for now, invested some ours, but actually no idea why it's crashing.

`2019-11-10 09:40:32.176 23206-23222/htcMAtravelCheckList.com E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
2019-11-10 09:40:32.287 23206-23206/htcMAtravelCheckList.com E/AndroidRuntime: FATAL EXCEPTION: main
    Process: htcMAtravelCheckList.com, PID: 23206
    java.lang.RuntimeException: Unable to start activity ComponentInfo{htcMAtravelCheckList.com/htcMAtravelCheckList.com.modules.mainView.MainActivityPro}: android.view.InflateException: Binary XML file line #54: Binary XML file line #54: Error inflating class com.github.clans.fab.FloatingActionButton
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: android.view.InflateException: Binary XML file line #54: Binary XML file line #54: Error inflating class com.github.clans.fab.FloatingActionButton
     Caused by: android.view.InflateException: Binary XML file line #54: Error inflating class com.github.clans.fab.FloatingActionButton
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:658)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at htcMAtravelCheckList.com.modules.mainView.MainActivity.onCreate(MainActivity.kt:135)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.NumberFormatException: For input string: "res/drawable/edit_text_material.xml"
2019-11-10 09:40:32.287 23206-23206/htcMAtravelCheckList.com E/AndroidRuntime:     at java.lang.Integer.parseInt(Integer.java:615)
        at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:133)
        at android.content.res.TypedArray.getInt(TypedArray.java:398)
        at android.view.animation.Animation.<init>(Animation.java:256)
        at android.view.animation.ScaleAnimation.<init>(ScaleAnimation.java:63)
        at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:199)
        at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:161)
        at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:142)
        at com.github.clans.fab.FloatingActionButton.initShowAnimation(FloatingActionButton.java:170)
        at com.github.clans.fab.FloatingActionButton.init(FloatingActionButton.java:151)
        at com.github.clans.fab.FloatingActionButton.<init>(FloatingActionButton.java:109)
        at com.github.clans.fab.FloatingActionButton.<init>(FloatingActionButton.java:104)
        	... 32 more
2019-11-10 09:40:32.313 1174-1185/? E/WindowManager: win=Window{a2a2dfb u0 Splash Screen htcMAtravelCheckList.com EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true`

**Comment by kolagit** [comment]
As stated, this library is not supported any longer.
To make it compatible with AndroidX, I had to make my own copy.
All you need to do is :
1. Copy all the java files
2. Copy all the files in res
3. update ImageView to use  "androidx.appcompat.widget.AppCompatImageView",
4. update ImageButton to use "androidx.appcompat.widget.AppCompatImageButton"
    (You have to fix one of super class constructor as AppCompatImageButton constructor 
    changed.)

It fixed the AndroidX compatibility issue for me.
