### ISSUE TITLE
Crashed on FloatingActionButton$ProgressSavedState

### ISSUE THREAD

**Issue by danpe** [Clans/FloatingActionButton#56]
A random crash appears when I open my app and my MainActivity calls it's child fragment with 
```Java
fragment.onCreate(savedInstanceSave)
```

Here is the full stack of the crash:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{activities.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.github.clans.fab.FloatingActionButton$ProgressSavedState
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.github.clans.fab.FloatingActionButton$ProgressSavedState
       at android.os.Parcel.readParcelableCreator(Parcel.java:2295)
       at android.os.Parcel.readParcelable(Parcel.java:2245)
       at android.os.Parcel.readValue(Parcel.java:2152)
       at android.os.Parcel.readSparseArrayInternal(Parcel.java:2546)
       at android.os.Parcel.readSparseArray(Parcel.java:1874)
       at android.os.Parcel.readValue(Parcel.java:2209)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
       at android.os.BaseBundle.unparcel(BaseBundle.java:221)
       at android.os.Bundle.getBundle(Bundle.java:733)
       at com.google.android.gms.maps.internal.cv.a(SourceFile:74)
       at com.google.maps.api.android.lib6.d.ft.a()
       at com.google.maps.api.android.lib6.d.ap.a()
       at com.google.android.gms.maps.internal.aa.onTransact(SourceFile:66)
       at android.os.Binder.transact(Binder.java:380)
       at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate()
       at com.google.android.gms.maps.MapView$zza.onCreate()
       at com.google.android.gms.dynamic.zza$3.zzb()
       at com.google.android.gms.dynamic.zza$1.zza()
       at com.google.android.gms.maps.MapView$zzb.zztD()
       at com.google.android.gms.maps.MapView$zzb.zza()
       at com.google.android.gms.dynamic.zza.zza()
       at com.google.android.gms.dynamic.zza.onCreate()
       at com.google.android.gms.maps.MapView.onCreate()
       at fragements.MapFragment.onCreateView(MapFragment.java:200)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1120)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1929)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
       at android.app.Activity.performStart(Activity.java:6006)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

Is anyone experiencing this also?

**Comment by fmendoza** [comment]
Yes, im facing the same problem. I have one fragment with mapview and the floating button

**Comment by h6ah4i** [comment]
@fmendoza That is a MapView's issue. Workaround is described [here](https://code.google.com/p/gmaps-api-issues/issues/detail?id=6237#c9).

**Comment by fmendoza** [comment]
Thanks @h6ah4i that solution is working fine
